<template>
  <div :class="['message', { dark }]">
    <h5 class="font-weight-bold text-capitalize">
      {{ author }}
      <span v-if="!autoGenerated">
        <font-awesome-icon v-if="author === 'user'" :icon="['fas', 'circle-user']" />
        <font-awesome-icon v-else :icon="['fas', 'robot']" />
      </span>
      <b-badge v-else variant="secondary" class="auto-badge"
        >Auto-Generated Message</b-badge
      >
    </h5>
    <span class="message-text"
      >{{ getDisplayedText
      }} <span v-if="!expanded"
        >
          <span @click="expandText" class="show-more-less">Show more</span>
          </span>
      </span>
      <span v-if="isLongAuthorMessage && this.expanded" @click="shortenText" class="show-more-less">Show less</span>
    <span v-if="gptLoading"
      ><b-spinner
        small
        label="Small Spinner"
        type="grow"
        variant="primary"
      ></b-spinner
      >&nbsp;<b-spinner
        small
        label="Small Spinner"
        type="grow"
        variant="primary"
      ></b-spinner
      >&nbsp;<b-spinner
        small
        label="Small Spinner"
        type="grow"
        variant="primary"
      ></b-spinner
    ></span>
    <div v-if="mindMap" class="mt-2">
      <b-button @click="showMindMap" variant="success">Open Mind Map</b-button>
    </div>
  </div>
</template>

<script>
const assistantIcon = require('../static/assistant.svg')
const userIcon = require('../static/user.svg')

export default {
  name: 'MessageComponent',
  props: [
    'text', // Content of the message
    'author', // Author of the message
    'dark', // Background variant of the box
    'gptLoading', // GPT is processing request
    'mindMap', // Boolean to check if mind map modal button should be shown
    'autoGenerated', // Boolean to check if message is auto generated in order to display badge
  ],
  data() {
    return {
      expanded: true,
    }
  },
  computed: {
    getIcon() {
      return this.author === 'user' ? userIcon : assistantIcon
    },
    isLongAuthorMessage() {
      return this.author === 'user' && this.text.length > 350
    },
    getDisplayedText() {
      if (this.author === 'user' && this.expanded) {
        return this.text
      } else if (this.isLongAuthorMessage) {
        return this.text.substring(0, 345) + '...'
      } else {
        return this.text
      }
    },
  },
  mounted() {
    if (this.isLongAuthorMessage) {
      this.expanded = false
    } else {
      this.expanded = true
    }
    this.$emit('scroll')
  },
  methods: {
    showMindMap() {
      this.$emit('showMindMap')
    },
    expandText() {
      this.expanded = true
    },
    shortenText() {
      this.expanded = false
    },
  },
}
</script>
<style scoped>
.message {
  font-family: 'Inconsolata', sans-serif;
  font-size: 1rem;
  background: #e7e7e7;
  color: #0f3559;
  border-radius: 10px;
  padding: 1rem;
  width: fit-content;
  max-width: 90%;
}

.message.dark {
  background: #0f3559;
  color: white;
}

h5 {
  margin: 0 0 0.4rem 0;
}

.author-icon {
  width: 1.25rem;
  height: 1.25rem;
  vertical-align: text-bottom;
}

.auto-badge {
  font-size: 0.75rem;
  padding: 0.25rem 0.5rem;
  vertical-align: text-bottom;
}

.message-text {
  font-size: 1.1rem;
  line-height: 1.5rem;
}

.show-more-less {
  color: #00a0e4;
  cursor: pointer;
  text-decoration: underline;
}
</style>
