<template>
  <div class>
    <b-navbar class="app-navbar" toggleable="lg" type="dark" variant="white">
      <b-navbar-brand class="navbar-brand" style="font-weight: bold; color: #45555f">
        <NuxtLogo style="margin: auto; cursor: pointer;" />
        <span class="nav-title">&nbsp; Mind Mapping In VR</span>
      </b-navbar-brand>
    </b-navbar>
    <b-container class="app-container col d-flex justify-content-center" fluid>
      <!-- Content here -->
      <b-card class="main-card">
        <!-- Landing Card -->
        <div v-if="!chat">
          <b-row class="main-card-row" style="">
            <b-col
              cols="12"
              xl="6"
              class="main-description"
              fluid
              style="overflow: auto; max-height: fit-content"
            >
              <h2 style="font-weight: bold">Mind Mapping in VR</h2>
              <br />
              <p>
                This Web App, developed by
                <a href="mailto:afonso.castelao@tecnico.ulisboa.pt"
                  >Afonso Muller e Sousa Castelão</a
                >
                represents the project to be delivered as his master's thesis on
                a Computer Science and Engineering degree in Instituto Superior
                Técnico, Lisbon.
              </p>
              <p>
                The app utilizes
                <a
                  href="https://platform.openai.com/docs/guides/gpt"
                  target="_blank"
                  >OpenAI's GPT</a
                >, a cutting-edge AI language model, to process text and
                generate a structured mind map. It analyzes the content,
                identifies important keywords and concepts, and arranges them
                hierarchically to create a clear mind map.
              </p>
              <p>
                Through the exchange of messages (prompts) with the GPT model, a
                Mind Map will be built. The user is able to keep chatting with
                the model in an informal way in order to achieve the desired
                result.
              </p>
              <p>
                The final mind map visualization and interaction is to be made
                in a Virtual Reality environment - through an external app
                called <a href="https://noda.io/" target="_blank">Noda.io</a>.
                When in that environment, the user is able to access this app’s
                generated Mind Map by importing it from Google Drive.
              </p>
              <div class="chat-button">
                <span v-if="windowWidth > 1199"
                  >To start chatting press the button:</span
                >
                <b-button variant="success" @click="activateChat"
                  >Start Chat</b-button
                >
              </div>
            </b-col>
            <b-col cols="12" xl="6">
              <div class="img-div">
                <b-img
                  class="mind-map-img"
                  src="https://media.istockphoto.com/id/1497860763/pt/vetorial/molecular-structure-icon.jpg?s=2048x2048&w=is&k=20&c=BbKEc9x9TMHYxWw5NOPk9igJg6Dpb2NzfU0Y9swB4i8="
                  fluid
                  alt="Mind Map ilustration image"
                />
              </div>
            </b-col>
          </b-row>
        </div>

        <!-- GPT Chat Card -->
        <div class="chat-card" v-else>
          <div style="display: flex; margin-bottom: -10px">
            <h4
              class="dark-blue-header ml-2"
              style="max-width: 67%; margin: auto"
            >
              GPT Chat Session:
            </h4>
            <b-button
              @click="$bvModal.show('confirm-new-chat-modal')"
              variant="secondary"
              style="
                color: rgb(77, 77, 77);
                padding: 0px auto;
                margin-left: auto;
                margin-right: 0;
              "
              ><font-awesome-icon :icon="['fas', 'circle-plus']" /> New
              Chat</b-button
            >
          </div>
          <hr />
          <b-row>
            <b-col cols="12" class="chat-col">
              <div class="messages">
                <Message
                  v-for="message in messages"
                  :key="message.id"
                  :class="['message', { right: message.isMine }]"
                  :dark="message.isMine"
                  :text="message.text"
                  :gptLoading="message.gptLoading"
                  :author="message.author"
                  :mindMap="message.mindMap"
                  :autoGenerated="message.autoGenerated"
                  @scroll="scrollToBottom"
                  @showMindMap="showModal"
                />
              </div>
              <ChatBox
                class="chat-box"
                @submit="onSubmit"
                @reset="handleReset"
              />
            </b-col>
          </b-row>
        </div>
      </b-card>
    </b-container>

    <!-- B-modal: Main Results Modal -->
    <b-modal
      ref="mind-map-modal"
      hide-footer
      no-close-on-backdrop
      title="Generated Mind Map"
      size="huge"
    >
      <div class="text-right mb-2">
        <b-button variant="secondary" @click="switchTable">
          <font-awesome-icon :icon="['fas', 'repeat']" />
          {{ showTable ? 'Toggle Graph View' : 'Toggle Table View' }}
        </b-button>
      </div>
      <div>
        <b-card
          class="d-block text-center w-75 ml-auto mr-auto"
          v-if="showTable"
        >
          <b-table
            striped
            hover
            :per-page="perPage"
            :current-page="currentPage"
            :items="mindMapData"
            small
          >
          </b-table>
          <b-pagination
            v-model="currentPage"
            :total-rows="totalRows"
            :per-page="perPage"
            align="fill"
            size="sm"
            class="my-0"
          ></b-pagination>
        </b-card>
        <b-card v-else class="d-block text-center">
          <div class="org-tree-div">
            <vue2-org-tree
              labelClassName="org-tree-nodes"
              :collapsable="false"
              :data="treeData"
            />
          </div>
        </b-card>
        <div class="mb-2">
          <hr />
          <div class="mt-2">
            <p class="mx-4 mb-0" style="font-size: large">
              Above you can observe the mind map that was generated based on the
              prompt.
            </p>
            <p
              v-if="!coordinatesGenerated"
              class="mx-4"
              style="font-size: large"
            >
              You can either modify and add information to the graph by chatting
              with the GPT model or opt to generate 3D coordinates for each
              node:
            </p>
            <p v-else class="mx-4" style="font-size: large">
              You can keep modifying or adding information to the graph by
              chatting with the GPT model. Once you are satisfied with the
              result, you can send the mind map to Google Drive by clicking the
              button below.
            </p>
          </div>
        </div>
        <div class="mt-3 d-flex">
          <div class="ml-0 mr-auto">
            <b-button variant="danger" @click="$bvModal.show('confirm-new-chat-modal')"
              ><font-awesome-icon :icon="['fas', 'circle-plus']" /> New Chat
            </b-button>
          </div>
          <div class="ml-auto mr-0" style="justify-content: flex-end">
            <b-button
              v-if="!coordinatesGenerated"
              variant="success"
              @click="generateCoordinates"
              ><font-awesome-icon :icon="['fas', 'diagram-project']" /> Generate
              Coordinates
            </b-button>
            <b-button variant="primary" @click="hideModal"
              ><font-awesome-icon :icon="['fas', 'comments']" /> Keep
              Chatting</b-button
            >
            <b-button
              v-if="coordinatesGenerated"
              variant="success"
              @click="$bvModal.show('send-to-g-drive-modal')"
              ><font-awesome-icon :icon="['fas', 'upload']" /> Send to Google
              Drive
            </b-button>
          </div>
        </div>
      </div>
    </b-modal>

    <!-- B-modal: GTP Response Error -->
    <b-modal
      ref="error-modal"
      centered
      hide-footer
      no-close-on-backdrop
      title="GPT Response Error"
      size="small"
    >
      <p>There seems to have been some kind of error from the GPT response.</p>
      <p>
        Since we're working with an AI model, it is expected that these errors
        happen sometimes.
      </p>
      <p>
        You can either retry to send the last message or start a new chat. In
        case the error keeps happening, please restart the chat.
      </p>
      <div class="d-flex">
        <div class="ml-0 mr-auto">
          <b-button variant="danger" @click="newChat"
            ><font-awesome-icon :icon="['fas', 'circle-plus']" /> New Chat
          </b-button>
        </div>
        <div class="ml-auto mr-0">
          <b-button variant="primary" @click="retryChat"
            ><font-awesome-icon :icon="['fas', 'arrow-rotate-left']" /> Retry
          </b-button>
        </div>
      </div>
    </b-modal>

    <!-- B-modal: Confirm New Chat -->
    <b-modal
      id="confirm-new-chat-modal"
      centered
      hide-footer
      no-close-on-backdrop
      title="Restart Chat"
      size="small"
    >
      <p>This action will erase any previous messages traded with the GPT Model and restart the conversation.</p>
      <p>
        Are you sure you would like to start a new chat?
      </p>
      <div class="d-flex">
        <div class="ml-0 mr-auto">
          <b-button variant="danger" @click="newChat"
            ><font-awesome-icon :icon="['fas', 'circle-plus']" /> New Chat
          </b-button>
        </div>
        <div class="ml-auto mr-0">
          <b-button @click="$bvModal.hide('confirm-new-chat-modal')" variant="primary"
            >Return <font-awesome-icon :icon="['fas', 'paper-plane']" style="color: #fff;" />
          </b-button>
        </div>
      </div>
    </b-modal>

    <!-- B-modal: Send Mind Map to Google Drive -->
    <b-modal
      id="send-to-g-drive-modal"
      centered
      hide-footer
      no-close-on-backdrop
      title="Export to Google Drive"
      size="small"
    >
      <p>Before sending the mind map, please verify that the resulted graph is formatted correctly.</p>
      <p>
        If that is the case, please give a name to the generated file and click the button below to send the mind map to Google Drive.
      </p>
      <b-form-group
        class="mt-2"
        id="mind-map-name"
        label="Mind Map Name:"
        label-for="name"
        description="Ensure that the mind map has no spaces or special characters."
      >
        <b-form-input
          id="name"
          v-model="mindMapName"
          type="text"
          placeholder="Enter mind map name"
          required
        ></b-form-input>
      </b-form-group>
      <br>
      <div class="d-flex">
        <div class="ml-0 mr-auto">
          <b-button :disabled="loading" @click="$bvModal.hide('send-to-g-drive-modal')" variant="primary"
            ><font-awesome-icon :icon="['fas', 'paper-plane']" style="color: #fff;" /> Return
          </b-button>
        </div>
        <div class="ml-auto mr-0">
          <b-spinner v-if="loading" small label="Small Spinner" variant="primary"></b-spinner>
          <b-button :disabled="loading || !this.mindMapName.length" variant="success" @click="doGDriveRequest"
            >Export to Google Drive <font-awesome-icon :icon="['fas', 'upload']" />
          </b-button>
        </div>
      </div>
    </b-modal>

  </div>
</template>

<script>
import ChatBox from '@/components/ChatBox.vue'
import Message from '@/components/Message.vue'

export default {
  name: 'MainPage',
  components: {
    ChatBox,
    Message,
  },
  data() {
    return {
      windowWidth: '',
      coordinatesGenerated: false,
      showTable: false,
      mindMapName: '',
      treeData: {
        label: 'root',
        expand: true,
        children: [
          { label: 'child 1' },
          {
            label: 'child 2',
            children: [{ label: 'child 4' }, { label: 'child 5' }],
          },
          { label: 'child 3' },
        ],
      },
      loading: false,
      rootNodeError: false,
      mindMapButton: false,
      totalRows: 1,
      currentPage: 1,
      perPage: 8,
      chat: false,
      id: 2,
      messages: [],
      gptHistory: [
        {
          role: 'system',
          content:
            "You are helping the User to build a Mind Map. The user will prompt for you to create a Mind Map based on a text input. When you have the information needed to build the mind map, please answer in the mind map format, such as: [{'NodeId': 'value', 'NodeName': 'value', 'FromNode': 'value', 'NodeLevel': 'value'}, {'NodeId': 'value', 'NodeName': 'value', 'FromNode': 'value', 'NodeLevel': 'value'}].",
        },
      ],
      mindMap: [],
    }
  },
  computed: {
    mindMapData() {
      return this.mindMap.length > 0 ? this.mindMap : []
    },
  },
  methods: {
    async activateChat() {
      this.chat = true

      if (!this.messages.length) {
        this.sendMessage({
          text: 'Hello!',
          role: 'user',
          gptLoading: false,
        })

        await this.requestToGpt('Hello!')
      }
    },
    async requestToGpt(message) {
      this.gptHistory.push({ role: 'user', content: message })
      this.sendMessage({
        text: '',
        role: 'assistant',
        gptLoading: true,
      })

      // Request to OpenAI
      const url = '/requestV2/' + 'test'
      await this.$axios
        .$post(url, this.gptHistory)
        .then((res) => {
          console.log(res)
          this.messages.pop()
          const gptAnswer = res.answer.text

          this.gptHistory.push({ role: 'assistant', content: gptAnswer })
          this.sendMessage({
            text: gptAnswer,
            role: res.answer.role,
            gptLoading: false,
          })

          this.checkMindMap(gptAnswer)
          this.checkConversationSize(res.answer.usage.total_tokens)
        })
        .catch((err) => {
          this.loading = false
          console.log(err)

          this.showErrorModal()
        })
    },
    // This method will be called when a new message is sent
    onSubmit(event, textv) {
      event.preventDefault()

      this.sendMessage({
        text: textv,
        role: 'user',
        gptLoading: false,
      })

      this.requestToGpt(textv)
    },
    sendMessage(message) {
      const mine = message.role === 'user'
      const auth = message.role
      this.messages.push({
        id: this.id,
        isMine: mine,
        text: message.text,
        author: auth,
        gptLoading: message.gptLoading,
        mindMap: JSON.stringify(message.mindMap),
        autoGenerated: message.autoGenerated
      })
      this.id++
      this.scrollToBottom()
    },
    handleReset() {
      this.chat = false
    },
    checkMindMap(gptAnswer) {
      this.rootNodeError = false

      if (gptAnswer.includes('NodeId')) {
        // Clean previous Mind Map buttons
        if (this.mindMapButton) {
          this.messages.forEach((element) => {
            element.mindMap = false
          })
        }

        // Flag used in case the GPT Answer contains only the mind map
        let mockMessage = false

        // Search for first '[' in gptAnswer
        const index = gptAnswer.indexOf('[')

        // Remove everything before '['
        gptAnswer = gptAnswer.substring(index)

        // Search for first ']' in gptAnswer
        const index2 = gptAnswer.indexOf(']')

        // Original Mind Map answer
        const unprocessedMindMap = gptAnswer.substring(0, index2 + 1)

        if (unprocessedMindMap.length === gptAnswer.length) {
          console.log('Will print generic message on chat.')
          mockMessage = true
        }

        // Remove everything after ']'
        gptAnswer = gptAnswer.substring(0, index2 + 1)

        // Replace None with "None" FIXME: Check for error here
        gptAnswer = gptAnswer.replace(' None', ' "None"')

        // Replace first single quotes (not in words) into double quotes
        gptAnswer = gptAnswer.replace(/(?<!\w)'/g, '"')

        // Replace last single quotes (not in words) into double quotes
        gptAnswer = gptAnswer.replace(/'(?!\w)/g, '"')

        console.log('Before Parse!!')
        console.log(gptAnswer)

        this.mindMap = JSON.parse(gptAnswer)
        this.totalRows = this.mindMap.length

        if (mockMessage) {
          this.messages[this.messages.length - 1].text =
            'The generated mind map content has been generated based on the information you provided.'
          this.messages[this.messages.length - 1].mindMap = true
        } else {
          const lastMessage = this.messages[this.messages.length - 1].text
          this.messages[this.messages.length - 1].text = lastMessage.replace(
            unprocessedMindMap,
            ''
          )
          this.messages[this.messages.length - 1].mindMap = true
        }

        console.log('ANSWER')
        console.log(gptAnswer)

        this.generateTree(this.mindMap)

        if (!this.rootNodeError) {
          this.mindMapButton = true
        }
        this.scrollToBottom()
      }
    },
    generateCoordinates() {
      this.hideModal()

      // Next time user opens mind map modal, it will be in table view
      this.showTable = true
      this.coordinatesGenerated = true

      const textv =
        'Can you please add three columns: "x", "y" and "z" which represent 3d coordinates of each node? Column z value should correspond to node level. Columns x and y should be floats between -1 and 4. Please fill them in order for the mind map be a force based graph. As always, take your time to compute a correctly formatted response (following the JSON format).'

      this.sendMessage({
        text: textv,
        role: 'user',
        gptLoading: false,
        autoGenerated: true
      })

      this.requestToGpt(textv)
    },
    async doGDriveRequest() {
      this.loading = true

      // Replace spaces with '_' on this.mindMapName
      this.mindMapName = this.mindMapName.replace(/\s/g, '_')
      
      const url = '/requestGDrive/' + this.mindMapName
      await this.$axios
        .$post(url, this.mindMap)
        .then(() => {
          this.loading = false

          this.$bvToast.toast('The Mind Map was sent to GDrive successfully!', {
            toastClass: 'mr-5',
            title: `Mind Map Sent Successfully`,
            variant: "success",
            autoHideDelay: 5000,
            solid: true,
            toaster: 'b-toaster-top-right'
          })

          this.$bvModal.hide('send-to-g-drive-modal')
        })
        .catch((err) => {
          this.loading = false

          this.$bvToast.toast('There was an error while sending the Mind Map to GDrive, please try again.', {
            toastClass: 'mr-5',
            title: `Error Sending to GDrive`,
            variant: "danger",
            autoHideDelay: 5000,
            solid: true,
            toaster: 'b-toaster-top-right'
          })

          console.log(err)
        })
    },
    scrollToBottom() {
      const container = this.$el.querySelector('.messages')
      if (container && container.scrollTop !== null) {
        container.scrollTop = container.scrollHeight
      }
    },
    showModal() {

      // Default Table page should be 1
      this.currentPage = 1
      this.$refs['mind-map-modal'].show()
    },
    hideModal() {
      this.$refs['mind-map-modal'].hide()

      // Default view should be graph view (except when user generates coordinates)
      if (this.showTable) {
        this.showTable = false
      }
    },
    showErrorModal() {
      this.$refs['error-modal'].show()
    },
    hideErrorModal() {
      this.$refs['error-modal'].hide()
    },
    generateTree(treeData) {
      // Firstly, sort tree by NodeLevel
      treeData.sort((a, b) => (+a.NodeLevel > +b.NodeLevel ? 1 : -1))

      const newData = treeData.map(({ NodeName: label, ...rest }) => ({
        label,
        ...rest,
      }))

      const map = new Map()

      // Create a mapping between NodeId and increasing integers
      for (let i = 0; i < newData.length; i++) {
        map.set(newData[i].NodeId, i)
      }

      // Replace NodeId and FromNode with map values
      for (let i = 0; i < newData.length; i++) {
        newData[i].NodeId = map.get(newData[i].NodeId)
        newData[i].FromNode = map.get(newData[i].FromNode)
      }

      const objsPerLevel = []

      // Then, create array of arrays of objects, per node level
      for (let i = 0; i < treeData.length; i++) {
        if (objsPerLevel[treeData[i].NodeLevel - 1] === undefined) {
          objsPerLevel[treeData[i].NodeLevel - 1] = []
        }
        objsPerLevel[treeData[i].NodeLevel - 1].push(treeData[i])
      }

      console.log('Data to parse')
      console.log(newData)

      this.list_to_tree(newData)
    },
    list_to_tree(list) {
      // console.log(list)

      const map = {}
      let node
      const roots = []
      let i

      for (i = 0; i < list.length; i += 1) {
        map[list[i].NodeId] = i // initialize the map
        list[i].children = [] // initialize the children
      }

      console.log(map)
      console.log(list)

      for (i = 0; i < list.length; i += 1) {
        node = list[i]
        if (
          node.FromNode !== '' &&
          node.FromNode !== null &&
          node.FromNode !== undefined &&
          node.FromNode !== 'None'
        ) {
          // if you have dangling branches check that map[node.FromNode] exists
          list[map[node.FromNode]].children.push(node)
        } else {
          roots.push(node)
        }
      }
      console.log('roots time')
      console.log(roots)
      if (roots.length > 1) {
        console.log('There are more than one root node. Printing message...')

        this.rootNodeError = true

        // Send automatic message to fix the issue and display toast
        this.fixMultipleNode()
      }
      this.treeData = roots[0]
      return roots
    },
    switchTable() {
      this.showTable = !this.showTable
    },
    async fixMultipleNode() {

      this.$bvToast.toast('GPT\'s response came with multiple root nodes. Sent automatic message in order to fix the issue.', {
        toastClass: 'mr-5 mt-5',
        title: `GPT Multiple Root Nodes Error`,
        variant: "warning",
        autoHideDelay: 10000,
        solid: true,
        toaster: 'b-toaster-top-right'
      })

      this.messages.forEach((element) => {
        element.mindMap = false
      })

      const textv =
        'There seems to be more than one root node. Can you rebuild the mind map, having only one root node? Take your time to compute a correctly formatted response (following the JSON format).'

      this.sendMessage({
        text: textv,
        role: 'user',
        gptLoading: false,
        autoGenerated: true
      })

      await this.requestToGpt(textv)
    },
    async retryChat() {
      this.hideErrorModal()
      console.log('Retrying chat')
      const textv =
        'The last response was invalid. Please take your time to compute a correctly formatted response (following the JSON format).'

      this.sendMessage({
        text: textv,
        role: 'user',
        gptLoading: false,
        autoGenerated: true
      })

      await this.requestToGpt(textv)
    },
    async newChat() {
      this.hideModal()
      this.hideErrorModal()
      this.$bvModal.hide('confirm-new-chat-modal')
      console.log('Reset on chat')

      this.coordinatesGenerated = false

      // This method is called on the syntax error modal
      // Reset and start a new chat.
      this.messages = []
      this.gptHistory = [
        {
          role: 'system',
          content:
            "You are helping the User to build a Mind Map. The user will prompt for you to create a Mind Map based on a text input. When you have the information needed to build the mind map, please answer in the mind map format, such as: [{'NodeId': 'value', 'NodeName': 'value', 'FromNode': 'value', 'NodeLevel': 'value'}, {'NodeId': 'value', 'NodeName': 'value', 'FromNode': 'value', 'NodeLevel': 'value'}].",
        },
      ]
      this.mindMap = []
      this.id = 2

      this.sendMessage({
        text: 'Hello!',
        role: 'user',
        gptLoading: false,
      })

      await this.requestToGpt('Hello!')
    },
    checkConversationSize(totalTokens) {
      if (totalTokens > 10000) {
        this.$bvToast.toast('The model\'s conversation limit is almost being reached. If you haven\'t, consider generate the coordinates and export the mind map to Google Drive.', {
          toastClass: 'mt-5',
          title: `Conversation Limit Almost Reached`,
          variant: "warning",
          autoHideDelay: 50000,
          solid: true,
          toaster: 'b-toaster-top-center'
        })

      }
    },
  },
  mounted() {
    this.windowWidth = window.innerWidth
  },
}
</script>

<style>
@import url('https://fonts.googleapis.com/css2?family=Nunito+Sans:opsz,wght@6..12,300&display=swap');

.modal .modal-huge {
  max-width: 95vw;
  width: 85vw;
  overflow: auto;
}

.org-tree-container {
  overflow: auto;
}

.chat-div {
  border: 2px solid #0f3559;
  margin-top: 5vh;
}

body {
  font-family: 'Nunito Sans', sans-serif;
  background-image: url('@/assets/img/background.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}

.app-navbar {
  height: fit-content;
}

.nav-title {
  font-size: 1rem;
  text-align: right;
}

.navbar-brand {
  display: flex;
  width: 100vw;
}

.main-row {
  margin-top: 5vh;
}

.main-form {
  height: 60vh;
  padding: 2%;
  color: rgb(69, 85, 95);
}

.main-card {
  margin-top: 10vh;
  padding: 0%;
  width: 90vw;
}

.main-description {
  padding: 1% 2%;
  height: 65vh;
  color: rgb(69, 85, 95);
  font-size: 20px;
  font-weight: bolder;
  text-align: justify;
}

.submit {
  display: flex;
  justify-content: flex-end;
}
.org-tree-nodes {
  background-color: #599cda;
  color: white;
  font-weight: bold;
  border-color: #599cda;
}
.org-tree-div {
  overflow: auto;
  max-height: 45vh;
}
.img-div {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;
}
.mind-map-img {
  margin-top: auto;
  margin-bottom: auto;
  max-width: 500px;
  max-height: 100%;
}

@media (min-width: 1501px) and (max-width: 1750px) {
  .main-description {
    font-size: 17px;
  }
}

@media (min-width: 1296px) and (max-width: 1500px) {
  .main-description {
    font-size: 17px;
  }
}

@media (min-width: 1200px) and (max-width: 1295px) {
  .main-description {
    font-size: 17px;
  }
  .mind-map-img {
    max-width: 400px;
  }
}

@media (max-width: 1199px) {
  .mind-map-img {
    max-width: 85vw;
    max-height: 70vh;
    height: fit-content;
    width: fit-content;
  }
  .main-description {
    height: fit-content;
    padding: 1% 4%;
  }
  .main-card {
    margin-top: 5vh;
    margin-bottom: 5vh;
    padding: 0%;
    width: 90vw;
    height: fit-content;
  }
  .app-navbar {
    height: fit-content;
  }
  h2 {
    text-align: center;
  }
  .app-container {
    height: 90vh;
  }
  .chat-button {
    text-align: center;
  }
}
</style>
<style scoped>
.dark-blue-header {
  color: #0f3559;
  font-weight: bold;
}
.chat-col {
  padding: 0 2% 0 2%;
  height: 60vh;
  display: flex;
  flex-direction: column;
}

.messages {
  flex-grow: 1;
  overflow: auto;
  padding: 1rem;
}

.message + .message {
  margin-top: 1rem;
}

.message.right {
  margin-left: auto;
}
</style>
